[WIP] Core skills screen - Implement screen UI & backend integration
stpopa/endava_profile_app pull request #18
Opened 2020-03-23 13:32 UTC by eparpalac

Demo: https://drive.google.com/file/d/14LM-BuU7k3s88R7_5PD6v_9Ou1lQEoDW/view?usp=sharing
Testing credentials: dude@mail.com/123123123

2020-03-23 14:01 UTC, ccosneanu requested changes

2020-03-23 14:01 UTC, ccosneanu commented on lib/modules/common/constants.dart
>    static const String HOME = '/';
i did refactor it, in `AppRoute`, lets use that.

2020-03-23 14:01 UTC, ccosneanu commented on lib/services/auth_service.dart
> +    String authToken = await FlutterKeychain.get(key: 'authToken');
Hurray we have persisted our token! ))

2020-03-23 14:04 UTC, ccosneanu commented
Oh, and this is kinda silly, but make sure to have 13 commits.

```zsh
git commit --allow-empty -m "+1 SP"
```

looks weird, but we already went for it.

2020-03-23 14:04 UTC, eparpalac commented on lib/modules/common/constants.dart
>    static const String HOME = '/';
ok, sure) I will resolve the conflicts and will change this

2020-07-04 10:11 UTC, ccosnean approved these changes

2020-07-19 12:42 UTC, merged